### ISSUE TITLE
Update to Optix 7.5.0

### ISSUE THREAD

**Issue by theoparis** [bartoszek/AUR-optix#1]
```
-> mv ~/Downloads/NVIDIA-OptiX-SDK-7.5.0-linux64-x86_64.sh .
AUR-optix on  master
-> makepkg -si
  -> Please manually download NVIDIA-OptiX-SDK-7.4.0-linux64-x86_64.sh to /home/theo/AUR-optix from https://developer.nvidia.com/designworks/optix/download.
```
![image](https://user-images.githubusercontent.com/11761863/193937995-308b0cd1-5a18-41f7-a9a0-c1a085814615.png)

**Comment by sausix** [comment]
Optix 7.4.0 is also buggy when using motion blur. Render time increases by factor 10! Also motion blur output version differs from CUDA with motion blur a alot.

Optix 7.6.0 is already out now. Seems to work. Output is quite the same compared to CUDA. And faster.

Why is blender-git pinning to Optix version 7.1.0? You can remove the version.

**Comment by bartoszek** [comment]
Let me test it, if blender:3.5 builds against optix:7.6 than it's no brainer to pin it lower 😒 
As far as I can tell it builds fine against optix:7.6 but officially only optix:7.4 is supported
So I'll push `optix74` to AUR and set `blender-git` optdepends=(optix>=7.4)
